image:
  - Visual Studio 2017
install:
  - set QTDIR=C:\Qt\5.12\msvc2017
  - set PATH=%PATH%;%QTDIR%\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
build_script:
  - qmake
  - nmake
  - cd release
  - windeployqt --no-compiler-runtime --no-translations --no-system-d3d-compiler --no-angle --no-opengl-sw --qmldir .. kis-ucp.exe 
  - del *.obj *.cpp *.h
artifacts:
  - path: release
    name: binaries